### ISSUE TITLE
 reports/characters_in_keys - showing:  "C" and "F" data at  the Tabs ( acute accent letters )

### ISSUE THREAD

**Issue by ImreSamu** [joto/taginfo#113]
The Taginfo Report "Characters in keys" is very usefull for data cleaning.

At now as I writing  [ http://taginfo.openstreetmap.hu/reports/characters_in_keys#statistics
we have cleaned the all problems at the 
* "Whitespace"  http://taginfo.openstreetmap.hu/reports/characters_in_keys#whitespace and
* "Problematic"  http://taginfo.openstreetmap.hu/reports/characters_in_keys#problematic

But we have type "C" and "E"  problems ..   Is it possible to  show ( at the future versions ) ?
( or maybe  is it possible to add a new config options to this report? http://taginfo.openstreetmap.hu/taginfo/config )

It is important for us (oms-hu ) , because type "C" maybe contains special Hungarian letters like "öÖüÜóÓőŐúÚéÉáÁűŰíÍ" and we need to clean them .. 

The statistics now - and  I would like to show the   count=132   "C" problems ..

  | Count | Fraction | Characters in key |
--- | ----- | -------- | --------------------------------------------------------
C |	132 |	7.21% |	Like B but with uppercase latin letters or letters from other alphabets.
D |	0 |	0.00% |	Like C but contains at least one whitespace character (space, tab, new line, carriage return, or from other alphabets).
E |	0 |	0.00% |	Like C but contains possibly problematic characters =+/&<>;'"?%#@\,.
F |	26 |	1.42%|	Everything else.

As I know  using  special accent at the key names - is "general  beginner problem" 
and maybe not only for  Hungarian mappers.    
see -->  http://en.wikipedia.org/wiki/Acute_accent

This is not critical and now we can query  with Overpass-api.  
But with Taginfo reports - we can show the typical problems to more people.

**Comment by joto** [comment]
I am not sure I understand what you are saying here. Do you want another tab with a table showing the category C keys?

**Comment by ImreSamu** [comment]
>Do you want another tab with a table showing the category C keys?

Yes !

and if useful for data cleaning process, one  another tab with a table showing the category F keys.

**Comment by joto** [comment]
The report now shows all categories A to F.

**Comment by ImreSamu** [comment]
Thank you!
