### ISSUE TITLE
Escaping for "+" "*" and "#"

### ISSUE THREAD

**Issue by brycenesbitt** [joto/taginfo#117]
Taginfo reports tags with  "+" "*" and "#"
https://taginfo.openstreetmap.org/reports/key_lengths
However the escaping is not right to actually load the nodes via JOSM or Overpass API.

Would it be possible to include object ID's in the page somewhere, if there are less than 50 or so nodes/ways/relations?

**Comment by joto** [comment]
Taginfo is not tracking IDs, the overhead would be too large. I'll look at the escaping and will try to fix it.

**Comment by brycenesbitt** [comment]
I've frequently wished that Taginfo would track the ID, at least the first
ID found.

**Comment by joto** [comment]
I have tried keys with '+', '*', and '#' in them and they all work in Overpass and JOSM. Please try again. Maybe the keys you tried were fixed by somebody else before you got around to it so it only looked as they were not loaded?

**Comment by brycenesbitt** [comment]
Looks like you're right.  There's another however:
taginfo.openstreetmap.org/keys/%E0%B8%B4building

That seems hard to find.  Here's where it would be super nice if for the 1 object key values, if
taginfo showed the OSM object identifier.

**Comment by joto** [comment]
https://wiki.openstreetmap.org/wiki/Taginfo/FAQ
