### ISSUE TITLE
Link to Level0 sometimes not working

### ISSUE THREAD

**Issue by mueschel** [joto/taginfo#118]
The linkto Level0 sometimes does not work at all, sometimes it takes several minutes until the new tab in the browser appears. Some feedback (like "processing request") would be nice.

**Comment by joto** [comment]
I am not sure how to handle this. I am just opening a new window/tab in the browser just like for any other link. If that site is slow, taginfo can't see that. In this case Overpass and Level0 are called, so if either or both sites are slow, this will happen.

**Comment by mueschel** [comment]
The tab only opens after a long time, so I guess it's overpass that doesn't react properly. 
I don't know why this query is made, you can pass any overpass query directly to Level0. This saves one additional call to overpass and makes the browser open the tab immediately (and then showing the usual "loading page" animation).

**Comment by joto** [comment]
Okay, I see the problem now. I do the Overpass query in taginfo and if that takes a long time or times out there is no info to the user. For some reason I can not get the Level0 editor to load the Overpass URL directly, so instead taginfo loads it, parses out node, way, and relation its and loads them into Level0.

@Zverik How is the URL supposed to look that makes Level0 load Overpass queries. With something like this http://level0.osmz.ru/?url=http://overpass.osm.rambler.ru/cgi/interpreter?data=[out:xml];%28node[%22Using%22];way[%22Using%22];rel[%22Using%22];%29;out%20meta;
I always get `Failed to open XML stream`.

**Comment by Zverik** [comment]
I think you should url-encode the url parameter. http://level0.osmz.ru/?url=http%3A%2F%2Foverpass.osm.rambler.ru%2Fcgi%2Finterpreter%3Fdata%3D%5Bout%3Axml%5D%3B%2528node%5B%2522Using%2522%5D%3Bway%5B%2522Using%2522%5D%3Brel%5B%2522Using%2522%5D%3B%2529%3Bout%2520meta%3B works.

**Comment by joto** [comment]
Ah, I see. I needed to url-encode this twice, first the Overpass URL parameter, then the Level0 URL parameter. Tricky :-)

**Comment by mueschel** [comment]
Looks promising - now one sees that something is going on. 
Could you add a recurse-down to the query? Would be very helpful to have the geometry of the way loaded in the editor.

**Comment by joto** [comment]
Not sure if thats a good idea. What if there are a hundred ways with 1000 nodes each?

**Comment by mueschel** [comment]
Sure, this is too much. Before the change Level0 did load the geometry, and usually Level0 was able to handle it. Taginfo shows the link only for less than 50 elements and Level0 puts a limit at 500 elements.

**Comment by joto** [comment]
I think this is something that has to be solved on the editor side. Maybe Level0 could get a button to get all nodes for the ways or whatever. But Level0 is really a simple editor for easy use cases, for more complex fixes I'd use JOSM anyway. I don't want to add functionality like this to taginfo.

**Comment by mueschel** [comment]
Sorry to say that, but that's a step backward. I'm currently doing some cleaning of keys using your new feature of similar tags, mostly on highways. It is very helpful to see how a way looks like, what it is connected to, etc. Without loading the nodes, Level0 can not show the way on the small inlay map any more. 
Before the change, you also asked for the recurse explicitly (by adding the '!' to ways):
`return el.type.substr(0,1) + el.id + (el.type == 'way' ? '!' : '');`
Why not doing it now as well?

Besides that: Keep up your great work with taginfo!

**Comment by joto** [comment]
Okay, okay, I have changed this to get the nodes again.

**Comment by mueschel** [comment]
:+1: Thanks!
