### ISSUE TITLE
"Has at least one wiki page" describes wrong thing

### ISSUE THREAD

**Issue by brycenesbitt** [joto/taginfo#122]
For http://taginfo.openstreetmap.org/keys/?key=denotation#values
Taginfo shows wiki pages for:

avenue  -
cluster  -
landmark  ✓

Because "landmark" has a tag page.  But here it's not a tag, it's a value.

**Comment by IrlJidel** [comment]
A tag is a key=value assignment

key: denotation
value:  landmark

tag:  denotation=landmark

A wiki page exists for denotation=landmark tag:

http://wiki.openstreetmap.org/wiki/Tag%3Adenotation%3Dlandmark
