### ISSUE TITLE
Frequently used keys without wiki page - checkbox results in an infinite work

### ISSUE THREAD

**Issue by matkoniecz** [joto/taginfo#123]
To reproduce: (1) open http://taginfo.osm.org/reports/frequently_used_keys_without_wiki_page (2) select "Also show keys that have no English language wiki page but a page in some other language. " checkbox (3) wait 20 minutes (4) page is still faded out with "Processing, please wait..."

Firefox 36.0.1 on Ubuntu 14.04.

**Comment by IrlJidel** [comment]
Confirmed on http://taginfo.openstreetmap.ie as well.

Logs show:

SQLite3::SQLException - no such column: in_wiki_en:
        /var/lib/gems/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:91:in `initialize'
        /var/lib/gems/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:91:in `new'
        /var/lib/gems/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:91:in `prepare'
        /var/lib/gems/1.9.1/gems/sqlite3-1.3.7/lib/sqlite3/database.rb:134:in `execute'

**Comment by IrlJidel** [comment]
Looks like this was removed in b9e7209f12e755881e9d9f951ba3f715fd4dab14

**Comment by joto** [comment]
Fixed.
