### ISSUE TITLE
do not show "✔" for keys with wikipages, if anything show the description from infobox

### ISSUE THREAD

**Issue by RicoZ-OSM** [joto/taginfo#127]
From comments on issue 66 I gather that the "✔" is pretty useless and it will not be a big loss when it is gone.

The description from the infobox which is much better anyway. If it could be displayed instead of the "✔" it would be great, otherwise just leave out that "✔".

**Comment by joto** [comment]
It shows that there is a wiki page which tells the users that they can investigate further there. The tables are already too wide in my opinion, no space for the description.
