### ISSUE TITLE
tagstats hits assertion in google sparse table

### ISSUE THREAD

**Issue by lonvia** [joto/taginfo#128]
While computing the daily stats for taginfo.osm.ch, tagstats has now twice failed with the following assertion:

~~~
Processing ways...
tagstats: /usr/include/google/sparsetable:1346: google::sparsetable<T, GROUP_SIZE, Alloc>::const_reference google::sparsetable<T, GROUP_SIZE, Alloc>::get(google::sparsetable<T, GROUP_SIZE, Alloc>::size_type) const [with T = unsigned int; short unsigned int GROUP_SIZE = 48u; Alloc = google::libc_allocator_with_realloc<unsigned int>; google::sparsetable<T, GROUP_SIZE, Alloc>::const_reference = const unsigned int&; google::sparsetable<T, GROUP_SIZE, Alloc>::size_type = long unsigned int]: Assertion `i < settings.table_size' failed.
Aborted (core dumped)
~~~

Contrary to what it says there was no core dumped.

This is not a regular event, it worked fine for three weeks or so between the crashes. The system is Ubuntu 14.04, Google Sparsetable is the standard repo version (1.10).

**Comment by joto** [comment]
This was due to a bug in osmium which has been fixed in 7f23002. Please recompile `tagstats` with the newest osmium.
