### ISSUE TITLE
Remove paging to improve searching

### ISSUE THREAD

**Issue by pmailkeey** [joto/taginfo#131]
![image](https://cloud.githubusercontent.com/assets/11827386/7541725/5390e960-f5af-11e4-9065-258edf67e1b2.png)

The wiki claims TI is supposed to be searchable but browsers cannot search across pages - so please put all results on one page.

**Comment by joto** [comment]
Use the search function of taginfo.

**Comment by pmailkeey** [comment]
Can anyone suggest a more useful, user-friendly means of searching for tags ?
