### ISSUE TITLE
Level0 not loading ways

### ISSUE THREAD

**Issue by malenki** [joto/taginfo#133]
When using the Level0 link quite often no data gets loaded.
Examples:
https://taginfo.openstreetmap.org/tags/tracktype=grade%201#
https://taginfo.openstreetmap.org/tags/tracktype=Mariedalsv%C3%A4gen

Tested with
Chromium 43.0.2357.65 Built on Debian stretch/sid, running on Debian stretch/sid (64-bit)
FF 38.0.1
Opera 30.0.1835.26

**Comment by joto** [comment]
In both cases you mentioned the overpass server used doesn't have that data for some reason. I am using http://overpass.osm.rambler.ru/. Maybe we should switch to http://overpass-api.de/ .
@drolbr any insights on this?

**Comment by drolbr** [comment]
Thank you for the notification. It looks like on the rambler instance the update process got hold.
See http://overpass.osm.rambler.ru/cgi/timestamp

I'll have a look what is going on. For the meantime, it is probably better to switch back to overpass-api.de

**Comment by malenki** [comment]
Roland Olbricht schrieb
am Sat, 30 May 2015 07:56:09 -0700:

> I'll have a look what is going on. For the meantime, it is probably
> better to switch back to overpass-api.de

I'd second this. Calling Level0  and not getting the data so often
is counter-useful to the simplicity of this tool.

Right now it wouldn't load https://www.openstreetmap.org/way/316001565
(via  https://taginfo.openstreetmap.org/tags/highway=tertirary)
