### ISSUE TITLE
Add a link to mapillary keys

### ISSUE THREAD

**Issue by pyrog** [joto/taginfo#134]
Hi,

Could you, please, add a link to Mapillary images to display pictures of objects ?
See [mapillary](http://wiki.openstreetmap.org/wiki/Key%3Amapillary) key.
Thank you :smile: 

See https://github.com/openstreetmap/openstreetmap-website/issues/986

**Comment by joto** [comment]
taginfo is not the right place to make special cases for some tags. Also see the comments in the issue you mention.
