### ISSUE TITLE
Codes appear when formatting is used in wiki text

### ISSUE THREAD

**Issue by pnorman** [joto/taginfo#136]
http://taginfo.openstreetmap.org/tags/shop=variety_store#wiki shows a description of "A en=variety store or price-point retailer...". The raw wiki text is "A '''variety store''' or price-point retailer"

**Comment by joto** [comment]
The description in the info box on the wiki should not use any formatting. I don't think we can solve this on the taginfo side.

**Comment by pnorman** [comment]
Ah, it's coming from the ValueDescription template. It has "A {{Template:Wikipedia|en|variety store|text=no}} or price-point retailer is a retail store that sells inexpensive items" there, which does seem odd.
