### ISSUE TITLE
Broken image on wiki tab, possibly commons related

### ISSUE THREAD

**Issue by pnorman** [joto/taginfo#137]
![image](https://cloud.githubusercontent.com/assets/1190866/8407461/8b1ad08c-1e1b-11e5-9eec-095ee1ebab7b.png)

It is linking to http://wiki.openstreetmap.org/w/images/thumb/3/34/100-Emon.jpg/180px-100-Emon.jpg 

The image itself is on Wikimedia commons, and https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/100-Emon.jpg/180px-100-Emon.jpg works

**Comment by joto** [comment]
This is fixed now. The reason why this broke again was the switch from http to https URLs.
