### ISSUE TITLE
Don't display checkmark in wiki-column for redirects

### ISSUE THREAD

**Issue by math1985** [joto/taginfo#150]
Currently, a checkmark column is displayed in the wiki column even if the wiki-page is merely a redirect. For example, leisure=hospital has a checkmark, while the corresponding (Portuguese) wiki page is only a forward to amenity=hospital.

The checkmark might lead a careless reader to think that the (incorrect) tag is in fact correct, like in the leisure=hospital example. Would it be possible to replace the checkmark by a different symbol, for example an arrow, when the wiki-page is merely a redirect?

Otherwise I think this is a really great project!

**Comment by joto** [comment]
"merely a redirect"? Unfortunately redirects are used for many things. It can me a misspelled tag redirecting to the correct spelling, it can be several perfectly valid tags redirecting to one page with a common description. Taginfo can't tell what's meant. This is not something that can be fixed in taginfo. Taginfo can only help you find those places and then you have to improve the Wiki. I suggest removing redirects from misspelled tags and such.

**Comment by math1985** [comment]
Are there any examples of valid tags with a redirect (like the redirect to a page with a common description you mention)?

Unfortunately there is no way to remove pages from the wiki, at least not without special permissions. Once there is a spelling mistake (such as [amenity=bicycke_parking](https://taginfo.openstreetmap.org/tags/amenity=bicycke_parking#wiki)), it will always stay there.

**Comment by joto** [comment]
@math1985: I don't remember a particular one, but I have seen them. To lazy to look for them now.

Mark the pages as candidates for deletion and sooner or later an admin will remove them. Use this template: http://wiki.openstreetmap.org/wiki/Template:Delete

**Comment by math1985** [comment]
So would it instead be possible to make a mention of the redirect in the Description tag within Taginfo?

Currently, for redirect pages, the Description in Taginfo is always empty, even if the redirect page has content. Perhaps the Description field in Taginfo could be filled with 'Redirect to $pagename'?

**Comment by math1985** [comment]
Alternatively, it would also work for me if Taginfo fetched the Description from the non-redirected page (request with &redirect=no).

**Comment by joto** [comment]
A redirect page shouldn't have any content. That doesn't make any sense at all.

**Comment by math1985** [comment]
So what about the idea to show it is a redirect? An empty description line is not helpul either.
