### ISSUE TITLE
wiki pages may be not detected and not listed in #wiki section

### ISSUE THREAD

**Issue by matkoniecz** [joto/taginfo#154]
http://taginfo.openstreetmap.org/keys/addr%3Aconscriptionnumber#wiki is not detecting http://wiki.openstreetmap.org/wiki/Key:addr:conscriptionnumber

**Comment by joto** [comment]
This is a general problem with lots of wiki pages due to a change in the Mediawiki API. Will be fixed at the next run tomorrow.
