### ISSUE TITLE
[translation]

### ISSUE THREAD

**Issue by thibdrev** [joto/taginfo#172]
On the [main page](http://taginfo.openstreetmap.org/), the following text can't be translated:
_"This is the main taginfo site. It contains OSM data for the whole planet and is updated daily."_

Same on the [About page](http://taginfo.openstreetmap.org/about/), the following text can't be translated:
_"This is the main taginfo site. It contains OSM data for the whole planet and is updated daily. This site is run by the OSMF and maintained by Jochen Topf and the Sysadmin team. Several other taginfo sites are operated by different people for different areas of the world."_

This is probably because these descriptions are tailored to each local server.

**Comment by joto** [comment]
Yes, that's the reason. A fix would mean that everbody running taginfo would have to supply those translations. I don't think this is important enough to worry about. But if somebody really wants this fixed, I am willing to look at pull requests.
