### ISSUE TITLE
Add Editor to tag pages

### ISSUE THREAD

**Issue by morray** [joto/taginfo#177]
It would be nice to see the distribution of editors involved in the cartoon of each tag. Since this might be more than one, probably the first and last edits should be counted in two separate diagrams

**Comment by joto** [comment]
To find out about the editor for each edited tag, we would need to look at changesets and full history. This is a huge effort on top of what we are doing now to create the taginfo statistics. Too much effort for something not needed that often. This could be something developed as an external program.
