### ISSUE TITLE
dublicate in projects of amenity=atm

### ISSUE THREAD

**Issue by it4workflow** [joto/taginfo#181]
https://taginfo.openstreetmap.org/tags/amenity=atm#projects: OSMaxx is listed twice?

**Comment by joto** [comment]
Osmaxx has this entry twice. Generally taginfo allows multiple entries for the same key, because they could have different details. But in this case it just seems an identical copy. Opened a bug report at https://github.com/geometalab/osmaxx-docs/issues/3.
